import Link from "next/link";
import { data } from "@/lib/data";
import { loadCensus, loadSources } from "@/lib/census";
import { pageMeta, SITE } from "@/lib/seo";
import { DATASET_BIBTEX, REPORT_APA, REPORT_BIBTEX } from "@/lib/cite";
import { CopyButton } from "@/components/copy-button";
import { ConfFigure, EdgeFigure, HeatFigure, RegisterFigure } from "@/components/figures";
import { SchemaFigure } from "@/components/schema-figure";
import { Toc } from "@/components/toc";
import { TraceList } from "@/components/trace-list";

const TITLE =
  "Suffeffix: an explainable lexical knowledge graph for morphology, semantic decomposition, etymology and affix alignment";

export const metadata = pageMeta({
  title: "Technical report v0.1",
  description:
    "How Suffeffix models words across a family boundary the data refuses to blur: sourced etymologies, a validator that rejects cross-family cognates, and explanations generated by named rules.",
  path: "/research/suffeffix-v0-1/",
  type: "article",
});

const SECTIONS = [
  { id: "summary", label: "Summary" },
  { id: "motivation", label: "1  Motivation" },
  { id: "graph", label: "2  The graph" },
  { id: "constraints", label: "3  Design constraints" },
  { id: "dataset", label: "4  The dataset" },
  { id: "explanations", label: "5  Explanations" },
  { id: "etymology", label: "6  Etymology and the boundary" },
  { id: "validation", label: "7  Validation" },
  { id: "limitations", label: "8  Limitations" },
  { id: "statement", label: "9  Data statement" },
  { id: "cite", label: "Cite this work" },
  { id: "references", label: "References" },
];

function H2({ id, n, children }: { id: string; n?: number; children: React.ReactNode }) {
  return (
    <h2 id={id} className="h-md">
      {n != null && <span className="mono block text-[12px] font-medium text-muted mb-2 tracking-wide">§ {n}</span>}
      {children}
    </h2>
  );
}

export default async function ReportPage() {
  const [c, sources, trace] = await Promise.all([loadCensus(), loadSources(), data.entry("lex:te:mancitanam")]);
  const crossTotal = c.edgeTypes.reduce((a, e) => a + e.crosses, 0);
  const share = (l: string, k: string) => Math.round((100 * (c.reg[l].counts[k] ?? 0)) / c.reg[l].n);
  const jsonLd = {
    "@context": "https://schema.org",
    "@type": "ScholarlyArticle",
    headline: TITLE,
    author: { "@type": "Organization", name: "Suffeffix contributors" },
    datePublished: "2026-09-30",
    inLanguage: "en",
    url: `${SITE.url}/research/suffeffix-v0-1/`,
    isAccessibleForFree: true,
    license: "https://creativecommons.org/licenses/by-sa/4.0/",
  };

  return (
    <>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} />

      {/* ── header ───────────────────────────────────────────── */}
      <header className="container pt-14 sm:pt-20 pb-12">
        <nav className="text-[13px] text-muted mb-8" aria-label="Breadcrumb">
          <Link href="/research/" className="hover:text-ink">Research</Link>
          <span className="mx-2 text-faint">/</span>
          <span>Technical report</span>
        </nav>
        <p className="kicker mb-6">Technical report · v0.1</p>
        <h1 className="h-lg max-w-[24ch]">{TITLE}</h1>
        <dl className="mt-10 grid gap-x-10 gap-y-5 sm:grid-cols-2 lg:grid-cols-4 border-t border-line pt-6 max-w-[64rem]">
          {[
            ["Authors", "Suffeffix contributors"],
            ["Published", "September 2026"],
            ["Version", "0.1.0 · all dataset records are drafts"],
            ["Licence", "Report and dataset CC BY-SA 4.0 · code Apache-2.0"],
          ].map(([k, v]) => (
            <div key={k}>
              <dt className="kicker mb-1.5">{k}</dt>
              <dd className="text-[14.5px] text-ink-2">{v}</dd>
            </div>
          ))}
        </dl>
        <div className="mt-9 flex flex-wrap gap-3 no-print">
          <Link href="/data/" className="btn btn-primary">Dataset &amp; downloads</Link>
          <a href={SITE.repo} className="btn btn-ghost">Source code</a>
          <a href="#cite" className="btn btn-ghost">Cite</a>
        </div>
      </header>

      <div className="container grid gap-x-16 gap-y-10 pb-24 xl:grid-cols-[13rem_minmax(0,1fr)]">
        <aside className="hidden xl:block">
          <div className="sticky" style={{ top: "calc(var(--header-h) + 28px)" }}>
            <Toc items={SECTIONS} />
          </div>
        </aside>

        <article className="paper min-w-0">
          {/* ── summary ──────────────────────────────────────── */}
          <section id="summary" aria-labelledby="summary-h">
            <h2 id="summary-h" className="kicker !m-0 !text-[11px] !font-medium !mb-5" style={{ fontSize: 11 }}>Abstract</h2>
            <p className="!text-[21px] !leading-[1.6] !text-ink !max-w-[62ch]">
              We present Suffeffix, a knowledge graph that jointly represents the morphology, semantic
              decomposition, etymology and cross-lingual affix alignment of {c.entries} words in English, Hindi and
              Telugu. Telugu is Dravidian; English and Hindi are Indo-European. The graph therefore treats the family
              boundary as a hard constraint: a validator rejects any cognate or inheritance edge that crosses it, and the
              resemblances that remain are modelled as borrowings. Every etymology edge carries a source and a confidence,
              contested etymologies are stored unresolved, and every explanation is generated by named template rules from
              graph facts — with a trace for each sentence and no language-model inference anywhere in the system. We release
              the v0.1 dataset, the validator and a static explorer.
            </p>

            <div className="not-prose grid gap-3 sm:grid-cols-2 lg:grid-cols-4 my-12">
              {[
                [String(c.entries), `words aligned across ${c.counts.concepts} meanings in three languages`],
                [String(c.counts.affixes), `affixes in ${c.counts.functions} cross-lingual functions`],
                [`${crossTotal} of ${crossTotal}`, "edges that cross a family boundary are borrowings; none are cognates"],
                [String(c.edgeTotal), `sourced etymology edges, ${c.contested} stored contested`],
              ].map(([n, l]) => (
                <div key={l} className="panel p-6">
                  <div className="h-md tnum leading-none">{n}</div>
                  <p className="!text-[13.5px] !leading-snug !text-muted !mt-3 !mb-0">{l}</p>
                </div>
              ))}
            </div>
          </section>

          {/* ── 1 motivation ─────────────────────────────────── */}
          <H2 id="motivation" n={1}>Why align words by function and by family</H2>
          <p>
            A bilingual dictionary tells you that <em>goodness</em>, <span lang="hi">अच्छाई</span> and{" "}
            <span lang="te">మంచితనం</span> mean the same thing. It does not tell you that each is built from a stem
            plus an abstract-state suffix, that the three suffixes are functional equivalents with different registers and
            reaches, or that two of the three languages share an ancestor the third does not. Those are exactly the facts a
            learner, a lexicographer or a computational linguist needs to reason about derivation across languages.
          </p>
          <p>
            Three things make that hard in this language set. Hindi and Telugu both carry a learned Sanskrit layer, so their
            vocabularies look more alike than their histories justify. English and Hindi share Indo-European ancestors that
            Telugu does not. And etymological claims vary enormously in how well they are supported. Suffeffix is an attempt
            to organise a small, auditable slice of this knowledge so that each of those distinctions is stored explicitly
            rather than left implicit in prose.
          </p>
          <p>
            Suffeffix builds on, and does not replace, existing resources: Natural Semantic Metalanguage primes seed its semantic
            atoms; reference works such as Turner’s <em>CDIAL</em>, Burrow and Emeneau’s <em>DEDR</em>, Monier-Williams and
            the <em>OED</em> are the sources it cites; and a WordNet interlingual identifier can be stored per meaning. Its
            contribution is the joint, validated structure, not new etymological scholarship.
          </p>

          {/* ── 2 graph ──────────────────────────────────────── */}
          <H2 id="graph" n={2}>The graph</H2>
          <p>
            The graph has eight node types in three layers. A <code>LexicalEntry</code> is a word in one language: its lemma in
            native script and transliteration, its register, and a morphological analysis — a stem and an ordered list of
            affix uses, each paired with the <em>function</em> it performs there. An <code>Affix</code> declares the functions it
            can perform, so “this entry uses this affix for this function” is checkable. An <code>EquivalenceClass</code> groups
            the affixes of different languages that perform one function. Each entry expresses a <code>Concept</code>, whose
            meaning is decomposed into a small closed inventory of atoms (<code>SemanticAtom</code>), and carries references to
            etymology edges (<code>EtymologyEdge</code>) that connect historical forms and reconstructed roots (<code>Root</code>).
          </p>
          <SchemaFigure
            n={1}
            c={c}
            caption={<><b>The schema.</b> Arrows read as relations; every reference is by identifier and checked by the validator. Counts are the v0.1 dataset, read from the same files that produce the downloads.</>}
          />

          {/* ── 3 constraints ────────────────────────────────── */}
          <H2 id="constraints" n={3}>Design constraints</H2>
          <h3>3.1 The family boundary is a rule, not a footnote</h3>
          <p>
            Every node of an etymology edge carries a <code>family</code>. The validator rejects any <code>COGNATE</code> or{" "}
            <code>INHERITED</code> edge whose endpoints fall in different top-level families, counting reconstructed
            Proto-Indo-European as Indo-European and Proto-Dravidian as Dravidian. English <em>mother</em>, Hindi{" "}
            <span lang="hi">माता</span> and Sanskrit <em>mātṛ</em> descend from one reconstructed ancestor and are linked as
            such; Telugu <span lang="te">అమ్మ</span> descends from a Proto-Dravidian nursery word and is deliberately not linked
            to them, however alike the sounds. What does link Telugu to the other two is borrowing — mostly from Sanskrit, from
            Perso-Arabic through Hindi and Urdu, and from English.
          </p>
          <h3>3.2 Register</h3>
          <p>
            Both Hindi and Telugu hold a native layer and a learned Sanskrit layer (<em>tatsama</em> against inherited{" "}
            <em>tadbhava</em> forms), and Hindi adds a Perso-Arabic layer. Each entry and affix therefore has a register —
            native, Sanskritic, Perso-Arabic, learned, or mixed — and affix equivalence prefers register-matched pairs. English
            reuses the “learned” value for its Latinate and Greek stratum, which is an engineering convention, not a claim from
            a reference work.
          </p>
          <h3>3.3 Every fact says how sure it is</h3>
          <p>Every content object carries one of four epistemic statuses, and a review status separate from it.</p>
          <table>
            <thead><tr><th>Status</th><th>Meaning</th></tr></thead>
            <tbody>
              <tr><td><strong>Established</strong></td><td>Standard linguistic knowledge, citable from reference works.</td></tr>
              <tr><td><strong>Engineering</strong></td><td>An abstraction chosen for implementation convenience; not a linguistic claim.</td></tr>
              <tr><td><strong>Hypothesis</strong></td><td>Plausible and testable, not yet demonstrated.</td></tr>
              <tr><td><strong>Future</strong></td><td>Out of scope for this release.</td></tr>
            </tbody>
          </table>
          <p>
            Every etymology edge requires a source and a confidence in [0, 1]. A claim supported only by Wiktionary is capped at
            0.6; a claim citing a reference work without an entry number is capped at 0.7, because we do not invent entry numbers.
            Where the literature disagrees — for instance whether Hindi <span lang="hi">कुत्ता</span> and Telugu{" "}
            <span lang="te">కుక్క</span> reflect a shared expressive or areal form — the edge is stored <code>contested</code>,
            badged wherever it appears, and left unresolved.
          </p>

          {/* ── 4 dataset ────────────────────────────────────── */}
          <H2 id="dataset" n={4}>The dataset</H2>
          <p>
            Version 0.1 contains {c.entries} words (English {c.reg.en.n}, Hindi {c.reg.hi.n}, Telugu {c.reg.te.n}) aligned across{" "}
            {c.counts.concepts} meanings, {c.counts.affixes} affixes (English {c.affixTotals.en}, Hindi {c.affixTotals.hi}, Telugu{" "}
            {c.affixTotals.te}) in {c.counts.functions} functions and {c.counts.classes} equivalence classes, {c.counts.atoms} semantic
            atoms, {c.counts.roots} reconstructed roots and {c.edgeTotal} etymology edges drawn from {c.counts.sources} cited
            sources. Every record is a draft.
          </p>
          <p>
            <strong>How the meanings were chosen matters for how to read the figures below.</strong> The meanings were selected to
            showcase derivational morphology and cross-family contrast — abstract states, agents, privatives, possessives, causatives,
            doctrines — plus a basic-vocabulary set for etymology demonstrations. The dataset is not a sample of any language, so the
            proportions below describe this selection, not English, Hindi or Telugu.
          </p>
          <RegisterFigure
            n={2}
            c={c}
            caption={<><b>Register layers.</b> Share of each language’s words by register in this selection: {share("te", "S")}% of the Telugu words are Sanskritic, Hindi is {share("hi", "N")}% native, {share("hi", "S")}% Sanskritic and {share("hi", "P")}% Perso-Arabic, and English is {share("en", "N")}% native with a {share("en", "E")}% learned stratum. Hover a segment for example words. Segment labels appear only where they fit; every value is also in the table view. Series colours were checked for colour-vision separation.</>}
          />
          <HeatFigure
            n={3}
            c={c}
            caption={<><b>Affix functions.</b> Number of affixes per language performing each cross-lingual function. Members of a row are functional equivalents, not translations: they differ in register, productivity and the bases they attach to. Blank cells mean the language has no affix for that function in this dataset, which can reflect the selection as much as the language.</>}
          />

          {/* ── 5 explanations ───────────────────────────────── */}
          <H2 id="explanations" n={5}>Explanations that show their working</H2>
          <p>
            The explanation for a word is assembled by a deterministic template engine from the entry’s morphology, its concept’s
            atom structure, its etymology edges and its alignments. Each sentence is produced by a named rule —{" "}
            <code>rule:morphology-chain</code>, <code>rule:atom-structure</code>, <code>rule:etymology-hop</code>,{" "}
            <code>rule:alignment</code> — and carries a trace of the affixes, atoms, edges and sources it used, with their
            confidences. The same input always yields the same output, and golden tests pin the output for ten entries.
            Where a concept’s decomposition is marked a hypothesis, the sentence says it “can be approximated as” rather than
            “is represented as”.
          </p>
          {trace && (
            <figure className="figure" id="fig-trace">
              <div className="figure-card">
                <h3 className="!mt-0 wide text-[19px] sm:text-[21px] font-semibold leading-snug max-w-[40ch]">
                  <span className="mono text-[12px] font-medium text-muted block mb-2 tracking-wide">FIGURE 4</span>
                  The generated explanation of <span lang="te">మంచితనం</span>, with its trace
                </h3>
                <div className="mt-6"><TraceList explanation={trace.explanation} /></div>
              </div>
              <figcaption className="figure-cap">
                <b>An explanation and its provenance.</b> Each chip is a node, rule or source the sentence depends on; affix and atom chips link into the graph.
                The explanation is generated, not written by hand, and is not offered as authoritative.
              </figcaption>
            </figure>
          )}
          <p>
            Freehand annotator notes are allowed but are stored and displayed separately, so a reader can always tell what the
            engine derived from what a person wrote.
          </p>

          {/* ── 6 etymology ──────────────────────────────────── */}
          <H2 id="etymology" n={6}>Etymology and the family boundary</H2>
          <p>
            The constraint in §3.1 is enforced at build time, so the corresponding figure shows the rule at work in the data
            rather than a result the data was free to contradict. Of {c.edgeTotal} edges, {c.edgeTypes.find((e) => e.type === "INHERITED")?.within}{" "}
            are inheritance and {c.edgeTypes.find((e) => e.type === "COGNATE")?.within} are cognacy, and none leaves its family.
            The {crossTotal} that do cross a boundary are all borrowings — among them <em>sugar</em>, which left Sanskrit three
            ways: inherited into Hindi, borrowed through Persian and Arabic into Latin, French and English, and borrowed into
            Telugu.
          </p>
          <EdgeFigure
            n={5}
            c={c}
            caption={<><b>Edges by type.</b> Grey segments stay within one family; violet segments cross a family boundary (Indo-European, Dravidian, Semitic, or an unclassified source). The validator guarantees there are no inherited or cognate edges in violet.</>}
          />
          <ConfFigure
            n={6}
            c={c}
            caption={<><b>Confidence.</b> The annotator’s confidence, binned to 0.05. Contested edges — red, with a dagger — sit at the low end by construction, because contested claims are given low confidence; the chart shows the policy was applied consistently, not that low confidence causes contestation. Hover a bar for counts.</>}
          />

          {/* ── 7 validation ─────────────────────────────────── */}
          <H2 id="validation" n={7}>Validation and reproducibility</H2>
          <p>The build fails if the dataset breaks any of the following rules:</p>
          <ul>
            <li>every identifier reference resolves, and identifiers follow their documented patterns;</li>
            <li>no cognate or inheritance edge crosses a top-level language family;</li>
            <li>every etymology edge cites a source that exists in the bibliography, and Wiktionary-only edges are capped at 0.6;</li>
            <li>every affix use names a function that the affix declares, in the entry’s own language;</li>
            <li>every concept is covered in each language or flagged as partially covered;</li>
            <li>entry, atom and function counts stay within their declared bounds, and no language outside English, Hindi and Telugu appears.</li>
          </ul>
          <p>
            Automated tests cover the validator (including deliberately malformed edges), search normalisation, the explanation
            engine’s golden outputs and every API route. The public site is a static export built from the exact responses of the
            read-only API, so the website, the API and the downloadable files cannot disagree. The code is open and the
            release carries SHA-256 checksums.
          </p>

          {/* ── 8 limitations ────────────────────────────────── */}
          <H2 id="limitations" n={8}>Limitations</H2>
          <ul>
            <li><strong>Everything is a draft.</strong> Records were authored against reference works but have not been reviewed item by item by domain experts. Treat them as hypotheses with citations.</li>
            <li><strong>Reference entry numbers are absent.</strong> CDIAL and DEDR are cited without entry numbers, which caps confidence at 0.7, until someone checks them against the printed volumes.</li>
            <li><strong>The selection is not a sample.</strong> {c.counts.concepts} meanings chosen to show derivation say little about the languages’ overall vocabulary, affix productivity or frequency.</li>
            <li><strong>Some analyses are judgement calls.</strong> Treating Telugu <span lang="te">-వాడు</span> as an affix, rather than a bound pronoun, or <span lang="te">-ఐన</span> as a suffix, is an engineering convenience and is tagged as such.</li>
            <li><strong>Atom structures are coarse.</strong> Decompositions of emotions and abstractions into at most fifty atoms are approximations, and many are marked hypotheses.</li>
            <li><strong>No sandhi, no frequency, three languages.</strong> Sandhi alternations are recorded only as allomorphs, there is no corpus frequency, and French and Tamil are planned for a later release.</li>
            <li><strong>English-only explanations.</strong> The template engine produces English sentences about all three languages.</li>
          </ul>

          {/* ── 9 statement ──────────────────────────────────── */}
          <H2 id="statement" n={9}>Data statement</H2>
          <p>
            The dataset contains no personal data. It describes words and word histories, and the discussion of language contact
            — in particular of Sanskrit, Perso-Arabic and English layers in Hindi and Telugu — is a historical-linguistic
            description, not a statement about any community. The dataset is released under CC BY-SA 4.0, the code under
            Apache-2.0. We especially welcome review by speakers and by specialists in Indo-Aryan and Dravidian linguistics, and
            corrections are best filed as issues against the repository, with the reference work cited.
          </p>

          {/* ── cite ─────────────────────────────────────────── */}
          <H2 id="cite">Cite this work</H2>
          <div className="not-prose grid gap-5 my-6">
            <div className="panel p-6">
              <div className="flex items-center justify-between mb-3"><span className="kicker">Technical report · BibTeX</span><CopyButton text={REPORT_BIBTEX} /></div>
              <pre className="mono text-[12.5px] leading-[1.7] overflow-x-auto">{REPORT_BIBTEX}</pre>
            </div>
            <div className="panel p-6">
              <div className="flex items-center justify-between mb-3"><span className="kicker">Dataset · BibTeX</span><CopyButton text={DATASET_BIBTEX} /></div>
              <pre className="mono text-[12.5px] leading-[1.7] overflow-x-auto">{DATASET_BIBTEX}</pre>
            </div>
            <div className="panel p-6">
              <div className="flex items-center justify-between mb-3"><span className="kicker">Plain text</span><CopyButton text={REPORT_APA} /></div>
              <p className="!text-[14.5px] !leading-relaxed !mb-0">{REPORT_APA}</p>
            </div>
          </div>
          <p>A machine-readable <code>CITATION.cff</code> is in the <a href={SITE.repo}>repository</a>.</p>

          {/* ── references ───────────────────────────────────── */}
          <H2 id="references">References</H2>
          <ol className="!pl-0 !list-none !max-w-none">
            {sources.map((s) => (
              <li key={s.id} className="!text-[14.5px] !leading-relaxed border-t border-line py-3 grid sm:grid-cols-[8rem_1fr] gap-x-6">
                <span className="mono text-[12px] text-muted pt-0.5">{s.id}</span>
                <span>{s.citation}</span>
              </li>
            ))}
          </ol>
        </article>
      </div>
    </>
  );
}
