import Link from "next/link";
import type { Explanation, TraceItem } from "@/lib/api";

const KIND_LABEL: Record<TraceItem["kind"], string> = {
  rule: "rule", affix: "affix", atom: "atom", edge: "edge", source: "source",
};

function traceHref(t: TraceItem): string | null {
  if (t.kind === "affix") return `/affixes/${t.ref.split(":").slice(1).join("/")}/`;
  if (t.kind === "atom") return `/atoms/${t.ref.replace(/^atom:/, "")}/`;
  return null;
}

/* Each generated sentence is a claim; opening it shows the graph nodes, named
   rules and sources that produced it. The first sentence starts open so the
   mechanism is visible without a click. */
export function ExplanationBlock({ explanation, notes }: { explanation: Explanation; notes?: string }) {
  return (
    <section>
      <div className="flex flex-wrap items-baseline justify-between gap-3 mb-2">
        <h2 className="wide text-[21px] font-semibold">How the graph explains it</h2>
        <span className="text-[12.5px] text-muted">generated by named rules · open a sentence to see why</span>
      </div>
      <p className="text-[13px] text-muted mb-4 max-w-[64ch]">
        These sentences are assembled from graph facts by a deterministic template engine — not written by
        hand, and not authoritative.
      </p>

      <ol className="border-y border-line divide-y divide-[var(--line)]">
        {explanation.sentences.map((s, i) => (
          <li key={i}>
            <details className="group" open={i === 0}>
              <summary className="cursor-pointer list-none py-4 grid grid-cols-[2rem_1fr_auto] gap-x-3 items-baseline">
                <span className="mono text-[12px] text-faint tnum">{String(i + 1).padStart(2, "0")}</span>
                <span className="text-[16px] leading-[1.6]">{s.text}</span>
                <span className="mono text-[11px] text-muted rounded-md border border-line px-1.5 py-0.5 whitespace-nowrap group-open:bg-sunk">
                  {s.trace.length} {s.trace.length === 1 ? "step" : "steps"}
                </span>
              </summary>
              <ul className="ml-[2.75rem] mb-4 rounded-lg bg-sunk px-4 py-3 space-y-1.5">
                {s.trace.map((t, j) => {
                  const href = traceHref(t);
                  return (
                    <li key={j} className="mono text-[12px] flex gap-3 items-baseline">
                      <span className="text-faint w-12 shrink-0">{KIND_LABEL[t.kind]}</span>
                      {href ? (
                        <Link href={href} className="text-ie-ink hover:underline underline-offset-2 break-all">
                          {t.ref}
                        </Link>
                      ) : (
                        <span className="text-ink-2 break-all">{t.ref}</span>
                      )}
                      {t.confidence < 1 && <span className="ml-auto text-muted tnum">{t.confidence.toFixed(2)}</span>}
                    </li>
                  );
                })}
              </ul>
            </details>
          </li>
        ))}
      </ol>

      {notes && (
        <aside className="mt-6 rounded-lg border border-dashed border-line-2 px-5 py-4">
          <p className="kicker mb-1.5">Annotator note · written by hand, not generated</p>
          <p className="text-[14.5px] leading-relaxed text-ink-2 max-w-[66ch]">{notes}</p>
        </aside>
      )}
    </section>
  );
}
