"""Build the public dataset release: CSV tables, a full JSON bundle, JSON Schemas,
a manifest with SHA-256 checksums, and a zip of everything.

Output: apps/web/public/data/ (served at /data/…, gitignored, regenerated by
`make site-data`). The /data/ page reads manifest.json, so what the page lists
is exactly what is downloadable.
"""

from __future__ import annotations

import csv
import hashlib
import json
import shutil
import sys
import zipfile
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "packages" / "core"))

from suffeffix_core.load import load_dataset  # noqa: E402
from suffeffix_core.schema import pretty_structure  # noqa: E402
from suffeffix_core.validate import validate_dataset  # noqa: E402

VERSION = "0.2.0"
OUT = ROOT / "apps" / "web" / "public" / "data"


def band(family: str) -> str:
    if family.startswith("Dravidian") or family == "Reconstructed:Proto-Dravidian":
        return "Dravidian"
    if family.startswith("IE") or family == "Reconstructed:PIE":
        return "Indo-European"
    return family


def write_csv(path: Path, header: list[str], rows: list[list]) -> int:
    # utf-8-sig so Excel opens Devanagari, Telugu and Tamil correctly
    with path.open("w", encoding="utf-8-sig", newline="") as f:
        w = csv.writer(f)
        w.writerow(header)
        w.writerows(rows)
    return len(rows)


def sha256(path: Path) -> str:
    h = hashlib.sha256()
    h.update(path.read_bytes())
    return h.hexdigest()


def main() -> None:
    ds = load_dataset()
    report = validate_dataset(ds)
    if not report.ok:
        raise SystemExit("dataset does not validate; refusing to publish a release:\n" + "\n".join(report.errors))

    if OUT.exists():
        shutil.rmtree(OUT)
    (OUT / "schema").mkdir(parents=True)

    concepts = {c.id: c for c in ds.concepts}
    rows_count: dict[str, int] = {}

    rows_count["entries.csv"] = write_csv(
        OUT / "entries.csv",
        ["id", "lang", "form", "transliteration", "pos", "register", "concept_id", "meaning", "stem",
         "affixes", "pattern", "segmentation_confidence", "etymology_edges", "review_status"],
        [[e.id, e.lang, e.lemma.form, e.lemma.translit, e.pos, e.register, e.concept_id,
          concepts[e.concept_id].gloss, e.morphology.stem_form,
          ";".join(f"{u.affix_id}|{u.function_id}" for u in e.morphology.affixes),
          e.morphology.schema_, e.morphology.segmentation_confidence,
          ";".join(e.etymology), e.provenance.review_status] for e in ds.entries],
    )
    rows_count["affixes.csv"] = write_csv(
        OUT / "affixes.csv",
        ["id", "lang", "form", "transliteration", "kind", "functions", "register", "productivity",
         "allomorphs", "attaches_to", "epistemic_status", "review_status"],
        [[a.id, a.lang, a.form, a.translit, a.kind, ";".join(a.functions), a.register, a.productivity,
          ";".join(a.allomorphs), ";".join(a.attaches_to), a.epistemic_status, a.provenance.review_status]
         for a in ds.affixes],
    )
    rows_count["etymology_edges.csv"] = write_csv(
        OUT / "etymology_edges.csv",
        ["id", "type", "from_form", "from_language", "from_family", "to_form", "to_language", "to_family",
         "crosses_family_boundary", "drift", "confidence", "status", "sources", "review_status"],
        [[e.id, e.type, e.from_.form, e.from_.lang_or_family, e.from_.family, e.to.form,
          e.to.lang_or_family, e.to.family, band(e.from_.family) != band(e.to.family),
          ";".join(d for d in e.drift if d != "NONE"), e.confidence, e.status,
          ";".join(e.source_ref), e.provenance.review_status] for e in ds.etymology_edges],
    )
    rows_count["atoms.csv"] = write_csv(
        OUT / "atoms.csv",
        ["id", "category", "definition", "nsm_prime", "english", "french", "hindi", "telugu", "tamil", "epistemic_status"],
        [[a.id, a.category, a.definition, a.nsm_prime, a.exponents.en, a.exponents.fr, a.exponents.hi, a.exponents.te,
          a.exponents.ta, a.epistemic_status] for a in ds.atoms],
    )
    rows_count["concepts.csv"] = write_csv(
        OUT / "concepts.csv",
        ["id", "meaning", "decomposition", "atoms", "decomposition_status", "partial_coverage"],
        [[c.id, c.gloss, pretty_structure(c.structure), ";".join(c.atoms), c.structure_status,
          c.partial_coverage] for c in ds.concepts],
    )
    rows_count["sources.csv"] = write_csv(
        OUT / "sources.csv",
        ["id", "title", "citation", "kind"],
        [[s.id, s.title, s.citation, s.kind] for s in ds.sources],
    )

    bundle = OUT / f"suffeffix-v{VERSION}.json"
    bundle.write_text(
        json.dumps({"version": VERSION, "generated": date.today().isoformat(),
                    **json.loads(ds.model_dump_json(by_alias=True))}, ensure_ascii=False),
        encoding="utf-8",
    )
    rows_count[bundle.name] = len(ds.entries)

    for src in sorted((ROOT / "docs" / "schema").glob("*.json")):
        if src.name != "openapi.json":
            shutil.copy(src, OUT / "schema" / src.name)

    for lic in ("LICENSE",):
        shutil.copy(ROOT / "data" / lic, OUT / "LICENSE.txt")
    (OUT / "README.txt").write_text(
        f"Suffeffix dataset v{VERSION}\n"
        "An explainable lexical knowledge graph: morphology, semantic decomposition, etymology and\n"
        "affix alignment for Telugu, Hindi, English, French and Tamil (the T.H.E.F.T. framework).\n\n"
        "Licence: CC BY-SA 4.0 (see LICENSE.txt). Cite: https://suffeffix.com/research/suffeffix-v0-2/#cite\n"
        "Status: every record is review_status=draft unless stated otherwise in the file.\n"
        "CSV files are UTF-8 with a byte-order mark so spreadsheets open Devanagari, Telugu and Tamil script correctly.\n"
        "List-valued columns use ';' between items; affix uses are 'affix_id|function_id'.\n"
        "SHA256SUMS.txt lists a checksum for every file.\n",
        encoding="utf-8",
    )

    files = sorted(p for p in OUT.rglob("*") if p.is_file())
    manifest_files = []
    for p in files:
        rel = p.relative_to(OUT).as_posix()
        manifest_files.append({"name": rel, "bytes": p.stat().st_size, "sha256": sha256(p),
                               "rows": rows_count.get(rel)})
    (OUT / "SHA256SUMS.txt").write_text(
        "".join(f"{m['sha256']}  {m['name']}\n" for m in manifest_files), encoding="utf-8")

    zpath = OUT / f"suffeffix-v{VERSION}.zip"
    with zipfile.ZipFile(zpath, "w", zipfile.ZIP_DEFLATED) as z:
        for p in files:
            z.write(p, f"suffeffix-v{VERSION}/{p.relative_to(OUT).as_posix()}")
    manifest_files.append({"name": zpath.name, "bytes": zpath.stat().st_size, "sha256": sha256(zpath), "rows": None})

    manifest = {
        "version": VERSION,
        "generated": date.today().isoformat(),
        "license": "CC BY-SA 4.0",
        "counts": {
            "entries": len(ds.entries), "concepts": len(ds.concepts), "affixes": len(ds.affixes),
            "affix_functions": len(ds.affix_functions), "atoms": len(ds.atoms),
            "etymology_edges": len(ds.etymology_edges), "roots": len(ds.roots), "sources": len(ds.sources),
        },
        "files": manifest_files,
    }
    (OUT / "manifest.json").write_text(json.dumps(manifest, indent=1), encoding="utf-8")
    print(f"release v{VERSION}: {len(manifest_files)} files -> apps/web/public/data "
          f"({sum(m['bytes'] for m in manifest_files) // 1024} KiB)")


if __name__ == "__main__":
    main()
