"""Export the API's responses as static JSON for the static site build.

Uses the FastAPI app via TestClient, so the API remains the literal contract:
the static site is built from exactly the payloads the live API would serve.
Output: apps/web/.sitedata/*.json (gitignored; regenerated by `make site-data`).
"""

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "packages" / "core"))
sys.path.insert(0, str(ROOT / "apps" / "api"))

from fastapi.testclient import TestClient  # noqa: E402

from suffeffix_api.main import app  # noqa: E402
from suffeffix_core.search import normalize  # noqa: E402

OUT = ROOT / "apps" / "web" / ".sitedata"
OUT.mkdir(exist_ok=True)


def main() -> None:
    with TestClient(app) as client:
        def get(path: str):
            r = client.get(path)
            r.raise_for_status()
            return r.json()

        def w(name: str, obj) -> None:
            (OUT / name).write_text(json.dumps(obj, ensure_ascii=False), encoding="utf-8")

        meta = get("/v0/meta")
        w("meta.json", meta)
        w("functions.json", get("/v0/affix-functions"))
        w("eq-classes.json", get("/v0/equivalence-classes"))
        w("atoms.json", get("/v0/atoms"))

        affixes = get("/v0/affixes")
        w("affixes.json", affixes)
        w("affix-details.json", {a["id"]: get(f"/v0/affixes/{a['id']}") for a in affixes})

        entries = get("/v0/entries?page=1")
        items = list(entries["items"])
        page = 2
        while len(items) < entries["total"]:
            items += get(f"/v0/entries?page={page}")["items"]
            page += 1
        w("entries.json", items)
        w("entry-details.json", {e["id"]: get(f"/v0/entries/{e['id']}") for e in items})
        w("atom-details.json", {a["id"]: get(f"/v0/atoms/{a['id']}") for a in get("/v0/atoms")})

        etym = {}
        for e in items:
            g = get(f"/v0/etymology/{e['id']}")
            if g["edges"]:
                etym[e["id"]] = g
        w("etymology.json", etym)

        # client-side search index (normalized in Python so TS stays trivial)
        details = json.loads((OUT / "entry-details.json").read_text(encoding="utf-8"))
        index = []
        for e in items:
            d = details[e["id"]]
            index.append({
                "id": e["id"], "lang": e["lang"], "form": e["form"],
                "translit": e["translit"], "gloss": e["gloss"], "pos": e["pos"],
                "register": e["register"],
                "nform": normalize(e["form"]), "ntranslit": normalize(e["translit"]),
                "ngloss": e["gloss"].lower(),
                "schema": d["entry"]["morphology"]["schema"],
            })
        pub = ROOT / "apps" / "web" / "public"
        pub.mkdir(exist_ok=True)
        (pub / "search-index.json").write_text(json.dumps(index, ensure_ascii=False), encoding="utf-8")

        print(f"exported {len(items)} entries, {len(affixes)} affixes, "
              f"{len(etym)} etymology graphs -> apps/web/.sitedata + public/search-index.json")


if __name__ == "__main__":
    main()
